puts "puts Poner string con salto de linea"
puts "print Poner string"
puts "+ Suma"
puts "- Resta"
puts "/ Divide"
puts "* Multiplica"
puts "% Porcentage"
puts "< Menor que"
puts "> Mayor que"
puts "<= Menor o iqual que"
puts ">= Mayor o igual que"
puts "<<PARAGRAPH  algo  PARAGRAPH  Sirve para dar formato de parrafo a un texto"
puts "gets.chomp() Obtener un string tecleado por el usuario"
puts "require Sireve para agregar caracteristicas al script o posicionar otras fuentes (Gemas o cosas escritas por uno mismo)"
puts "ARGV dar de alta variables en un argumento"
puts "STDIN.gets.chop() btener un string tecleado por el usuario"
puts "<<MESSAGE  algo  MESSAGE  Sirve para poner un mensage"
puts "File.open(nom_archivo)  Utilizado para abrir documentos de texto"
puts "nom_archivo.read()  Se utiliza para leer un documento de texto"
puts "File.open(nom_archivo, 'W') Se usa para eliminar el contenido de un archivo"
puts "archivo.truncate(nom_archivo.size)  Se utiliza para truncar el tamaño de archivo"
puts "archivo.write(linea)  Escribir un documento"
puts "archivo.close() Cerrar documento"
puts "archivo.length longitud del archivo"
puts "archivo.seek longitud del archivo"
puts "archivo.readline leer linea de un documento"
puts "def nom_metodo(*args)\n\tcontenido del metodo\nend\n  definir un metodo"
